name: SilentJoin
main: me.james.silentjoin.SilentJoin
version: 1.0
api-version: 1.16
description: Allows admins to join silently
author: James
permissions:
  silentjoin.use:
    description: Allows silent join
    default: op